env:
  browser: true
  es6: true
  jest: true
extends:
  - airbnb
parser: babel-eslint

plugins:
  - react
  - jsx-a11y
  - import

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/interactive-supports-focus: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  object-curly-newline: 0
  react/jsx-one-expression-per-line: 0
  arrow-body-style: 0

settings:
  import/resolver:
    webpack:
      config: webpack.dev.js

