version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - cp -r public/ dist/public/
      - aws s3 sync --quiet dist/ s3://$BUCKET/html/
